name: 🚀 Build and Deploy React to Hostinger

on:
  push:
    branches:
      - main  # Triggers the automation every time you push to the 'main' branch

jobs:
  web-deploy:
    name: 🎉 Compile and Upload
    runs-on: ubuntu-latest
    steps:
    
    - name: 🚚 Get latest code
      uses: actions/checkout@v6 # 👈 Updated to v6 to support Node 24 natively

    - name: 🟢 Setup Node.js
      uses: actions/setup-node@v6 # 👈 Updated to v6 to support Node 24 natively
      with:
        node-version: '24' # 👈 Changed from 20 to 24

    - name: 🔨 Install dependencies and Build
      run: |
        cd frontend
        npm install
        npm run build

    - name: 📂 Deply via SFTP to Hostinger
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: 217.21.83.210
        port: 22
        local_path: ./frontend/dist/*
        remote_path: /home/${{ secrets.FTP_USERNAME }}/public_html/reviews/
        sftpArgs: '-o ConnectTimeout=5'