name: 🚀 Build and Deploy React to Hostinger

on:
  push:
    branches:
      - main  # Triggers the automation every time you push to the 'main' branch

jobs:
  web-deploy:
    name: 🎉 Compile and Upload
    runs-on: ubuntu-latest
    steps:
    
    - name: 🚚 Get latest code
      uses: actions/checkout@v6 # 👈 Updated to v6 to support Node 24 natively

    - name: 🟢 Setup Node.js
      uses: actions/setup-node@v6 # 👈 Updated to v6 to support Node 24 natively
      with:
        node-version: '24' # 👈 Changed from 20 to 24

    - name: 🔨 Install dependencies and Build
      run: |
        cd frontend
        npm install
        npm install 
        npm run build

    - name: 📂 Sync Dist Folder to Hostinger Subdomain
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: 217.21.83.210 # 👈 Keep your Hostinger FTP Host here
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./frontend/assets/   # 👈 Change to ./build/ if using Create React App instead of Vite
        server-dir: ./public_html/reviews/ # 👈 Keep your subdomain path here